name: Deploy to EC2

on:
  workflow_call:
    inputs:
      image_uri:
        required: true
        type: string
      ecr_registry:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Develop

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy container via SSM
        id: ssm
        run: |
          DB_CONN="Host=${{ vars.DB_HOST }};Port=${{ vars.DB_PORT }};Database=${{ vars.DB_NAME }};Username=${{ secrets.DB_USERNAME }};Password=${{ secrets.DB_PASSWORD }};Pooling=true;Persist Security Info=true;"
          REDIS_CONN="${{ secrets.REDIS_HOST }}:${{ vars.REDIS_PORT }}"
          CONTAINER_NAME="empreganet-api"
          APP_PORT="80:8080"
          IMAGE_URI="${{ inputs.image_uri }}"
          ECR_REGISTRY="${{ inputs.ecr_registry }}"

          COMMAND_ID=$(aws ssm send-command \
            --region "${{ vars.AWS_REGION }}" \
            --instance-ids "${{ vars.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Docker container" \
            --query "Command.CommandId" \
            --output text \
            --parameters "commands=[
              \"set -e\",
              \"aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY\",
              \"docker pull $IMAGE_URI\",
              \"docker stop $CONTAINER_NAME || true\",
              \"docker rm $CONTAINER_NAME || true\",
              \"docker run -d --name $CONTAINER_NAME --restart always -p $APP_PORT -e ConnectionStrings__PostgreSQLConnection='$DB_CONN' e Redis='$REDIS_CONN' $IMAGE_URI\"
            ]")

          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

      - name: Fetch SSM execution logs
        run: |
          echo "Waiting for SSM command to finish..."
          sleep 10

          aws ssm get-command-invocation \
            --region "${{ vars.AWS_REGION }}" \
            --command-id "${{ steps.ssm.outputs.command_id }}" \
            --instance-id "${{ vars.EC2_INSTANCE_ID }}"
