name: Deploy to EC2

on:
  workflow_call:
    inputs:
      image_uri:
        required: true
        type: string
      ecr_registry:
        required: true
        type: string

env:
  CONTAINER_NAME: empreganet-api
  APP_PORT: "80:8080"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Develop

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy container via SSM
        shell: bash
        env:
          IMAGE_URI: ${{ inputs.image_uri }}
          ECR_REGISTRY: ${{ inputs.ecr_registry }}
          DB_CONN: Host=${{ secrets.DB_HOST }};Port=${{ vars.DB_PORT }};Database=${{ vars.DB_NAME }};Username=${{ secrets.DB_USERNAME }};Password=${{ secrets.DB_PASSWORD }};Connect Timeout=240;TrustServerCertificate=True
          REDIS_CONN: ${{ secrets.REDIS_HOST }}:${{ vars.REDIS_PORT }}
        run: |
          set -e

          [ -z "$IMAGE_URI" ] && echo "IMAGE_URI is empty" && exit 1

          aws ssm send-command \
            --instance-ids "${{ vars.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --region "${{ vars.AWS_REGION }}" \
            --comment "Deploy API EmpregaNet" \
            --parameters "commands=[
              \"set -e\",
              \"aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY\",
              \"docker pull $IMAGE_URI\",
              \"docker stop $CONTAINER_NAME || true\",
              \"docker rm $CONTAINER_NAME || true\",
              \"docker run -d --restart always --name $CONTAINER_NAME -p $APP_PORT -e ConnectionStrings__PostgreSQLConnection='$DB_CONN' -e Redis='$REDIS_CONN' $IMAGE_URI\"
            ]"
