name: Push Image to ECR

on:
  workflow_call:
    outputs:
      image_uri:
        value: ${{ jobs.push-image.outputs.image_uri }}
      ecr_registry:
        value: ${{ jobs.push-image.outputs.ecr_registry }}

env:
  ECR_REPOSITORY: empreganet-api

jobs:
  push-image:
    runs-on: ubuntu-latest

    outputs:
      image_uri: ${{ steps.publish.outputs.image_uri }}
      ecr_registry: ${{ steps.publish.outputs.ecr_registry }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - id: image-push
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI_SHA="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          IMAGE_URI_LATEST="$ECR_REGISTRY/$ECR_REPOSITORY:latest"

          dotnet publish \
            -c Release \
            -p:PublishProfile=DefaultContainer \
            -p:RuntimeIdentifier=linux-x64 \
            -p:ContainerRegistry=$ECR_REGISTRY \
            -p:ContainerImageName=$ECR_REPOSITORY \
            -p:ContainerImageTag=$IMAGE_TAG

          docker tag "$IMAGE_URI_SHA" "$IMAGE_URI_LATEST"

          docker push "$IMAGE_URI_SHA"
          docker push "$IMAGE_URI_LATEST"

          echo "image_uri=$IMAGE_URI_SHA" >> "$GITHUB_OUTPUT"
          echo "ecr_registry=$ECR_REGISTRY" >> "$GITHUB_OUTPUT"
